
services:

  mongodb:
    image: mongo:8.0.3
    environment:
      MONGO_INITDB_ROOT_USERNAME: dev
      MONGO_INITDB_ROOT_PASSWORD: dev
    ports:
    - "27017:27017"
    restart: always
    volumes:
    - mongodb-store:/data/db
    networks:
    - main

  mongo-express:
    image: mongo-express
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: dev
      ME_CONFIG_MONGODB_ADMINPASSWORD: dev
      ME_CONFIG_MONGODB_URL: mongodb://dev:dev@mongodb:27017/
      ME_CONFIG_BASICAUTH: false
    ports:
    - "9000:8081"
    restart: always
    networks:
    - main

  rabbitmq:
    image: rabbitmq:4-management
    environment:
      RABBITMQ_DEFAULT_USER: dev
      RABBITMQ_DEFAULT_PASS: dev
    ports:
    - "5672:5672"   # RabbitMQ broker port
    - "15672:15672" # RabbitMQ management console
    restart: always
    networks:
      main:

volumes:
  mongodb-store:
    driver: local

networks:
  main:
