---

debug: true
name: 'OrbidiMapMyWorld'

mongodb:
  url: "mongodb://dev:dev@localhost:27017/"
  database: 'myworld'

celery:
  broker_url: 'amqp://dev:dev@localhost:5672//'

faststream:
  url: 'amqp://dev:dev@localhost:5672//'
  app_id: 'map-my-world'
  exchange_name: 'eventsource'
